version: '3.1'
services:
        mongodb:
                image: mongo
                container_name: mongodb-container
                ports:
                        - "27017:27017"
                volumes:
                        - ./data:/data/db